#spring.application.name=department
#spring.security.user.name=meena
#spring.security.user.password=microservices
spring:
  application:
    name: department-service
#  config:
#    import: "optional:configserver:http://localhost:8088"
#  security:
#    user:
#      name: admin
#      password: meena